kafka:
  brokers:
    - "localhost:9092"
    - "localhost:9093"
    - "localhost:9094"
  writer:
    topic: "image-recognition-requests"
  reader:
    topic: "image-recognition-responses"
    groupID: "image-recognition-responses-group"